wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1664044161.206169
    t:
      1:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      2:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 5
