wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1663195767
    t:
      1:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      3:
      - 16
      4: 3.9.7
      5: 0.12.21
      8:
      - 5
datamodule:
  desc: null
  value: {}
dataset:
  desc: null
  value: {}
etl:
  desc: null
  value: {}
init:
  desc: null
  value:
    PROJECT: my-project
