wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    mask/class_labels:
      image_key_wandb_delimeter_ground_truth:
        key: image_key_wandb_delimeter_ground_truth
        type: mask/class_labels
        value:
          '0': bone
          '1': background
      image_key_wandb_delimeter_predictions:
        key: image_key_wandb_delimeter_predictions
        type: mask/class_labels
        value:
          '0': bone
          '1': background
    python_version: 3.9.7
    start_time: 1664058405.355296
    t:
      1:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      2:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      3:
      - 2
      - 13
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 5
